name: Run Unit Tests

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build_and_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure CMake
      run: cmake -B ${{github.workspace}}/build -S "${{github.workspace}}/test" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ./Release/test
